version: "3"

volumes:
  dbbackups:
  postgis-data:

services:
   postgres:
    image: postgres:latest
    volumes:
      - postgis-data:/var/lib/postgresql
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
        POSTGRES_DB: "forum"
        POSTGRES_USER: "mikhail"
        POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
